#include "../header/globals.h"
FragmentBuffer g_final_mix_pass_fbo;
FragmentBuffer g_main_game_pass_fbo;
FragmentBuffer g_gaussian_blur_pass_fbo;
FragmentBuffer g_gaussian_blur_vertical_pass_fbo;
FlameRenderPass g_flame_render_pass;
FragmentBuffer g_point_render_pass_fbo;
Timer g_main_timer;
std::queue<Operation> g_main_operation;